### ISSUE TITLE
index does not exists when I do http://localhost:9200/rethinkdbname/rethinkdoc/_search?q=eMail:nikola

### ISSUE THREAD

**Issue by goors** [rethinkdb/elasticsearch-river-rethinkdb#12]
I got the error:
<pre>
{
    "error": "IndexMissingException[[rethinkdbname] missing]",
    "status": 404
}

</pre>

when trying to search http://localhost:9200/rethinkdbname/rethinkdoc/_search?q=eMail:nikola

http://localhost:9200/_river/rethinkdb/_meta gives me:

<pre>
{
    "_index": "_river",
    "_type": "rethinkdb",
    "_id": "_meta",
    "_version": 4,
    "found": true,
    "_source": {
        "type": "rethinkdb",
        "rethinkdb": {
            "databases": {
                "rethinkdbname": {
                    "rethinkdoc": {
                        "backfill": true
                    }
                }
            },
            "host": "localhost",
            "port": 28015,
            "auth_key": "4f752a0aac5a1a2ed0a6627854d174facb99dc36cd756776b609e9cb8dcce275"
        }
    }
}
</pre>

**Comment by goors** [comment]
I can see that elastics is ignoring plugin from log:

<pre>
failed to load plugin from [file:/usr/share/elasticsearch/plugins/river-rethinkdb/es-plugin.properties]
org.elasticsearch.ElasticsearchException: Failed to load plugin class [org.elasticsearch.plugin.river.rethinkdb.RethinkDBRiverPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:516)
	at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:397)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:100)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:143)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:68)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:201)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.UnsupportedClassVersionError: org/elasticsearch/plugin/river/rethinkdb/RethinkDBRiverPlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:499)

</pre>

**Comment by goors** [comment]
My rethinkdb version is
<pre> rethinkdb 2.2.5~0jessie (GCC 4.9.2) </pre>

**Comment by goors** [comment]
Sorry, i can see that this will not work with 2.2
